export const DEVICE_ACTIONS = {
  DISCOVER_DEVICES_REQUEST: 'device/DISCOVER_DEVICES_REQUEST',
  DISCOVER_DEVICES_SUCCESS: 'device/DISCOVER_DEVICES_SUCCESS',
  DISCOVER_DEVICES_FAILURE: 'device/DISCOVER_DEVICES_FAILURE',
  
  PAIR_DEVICE_REQUEST: 'device/PAIR_DEVICE_REQUEST',
  PAIR_DEVICE_SUCCESS: 'device/PAIR_DEVICE_SUCCESS',
  PAIR_DEVICE_FAILURE: 'device/PAIR_DEVICE_FAILURE',
  
  UNPAIR_DEVICE_REQUEST: 'device/UNPAIR_DEVICE_REQUEST',
  UNPAIR_DEVICE_SUCCESS: 'device/UNPAIR_DEVICE_SUCCESS',
  UNPAIR_DEVICE_FAILURE: 'device/UNPAIR_DEVICE_FAILURE',
  
  SELECT_DEVICE: 'device/SELECT_DEVICE',
  UPDATE_DEVICE_STATUS: 'device/UPDATE_DEVICE_STATUS',
} as const;

export const AUTH_ACTIONS = {
  LOGIN_REQUEST: 'auth/LOGIN_REQUEST',
  LOGIN_WITH_GOOGLE: 'auth/LOGIN_WITH_GOOGLE',
  LOGIN_SUCCESS: 'auth/LOGIN_SUCCESS',
  LOGIN_FAILURE: 'auth/LOGIN_FAILURE',
  REGISTER_REQUEST: 'auth/REGISTER_REQUEST',
  REGISTER_SUCCESS: 'auth/REGISTER_SUCCESS',
  REGISTER_FAILURE: 'auth/REGISTER_FAILURE',
  LOGOUT: 'auth/LOGOUT',
  LOGOUT_SUCCESS: 'auth/LOGOUT_SUCCESS',
  AUTH_STATE_CHANGED: 'auth/AUTH_STATE_CHANGED',
} as const;

export const MEDIA_ACTIONS = {
  FETCH_MEDIA_REQUEST: 'media/FETCH_MEDIA_REQUEST',
  FETCH_MEDIA_SUCCESS: 'media/FETCH_MEDIA_SUCCESS',
  FETCH_MEDIA_FAILURE: 'media/FETCH_MEDIA_FAILURE',
  
  DELETE_MEDIA_REQUEST: 'media/DELETE_MEDIA_REQUEST',
  DELETE_MEDIA_SUCCESS: 'media/DELETE_MEDIA_SUCCESS',
  DELETE_MEDIA_FAILURE: 'media/DELETE_MEDIA_FAILURE',
  
  SET_MEDIA_FILTER: 'media/SET_MEDIA_FILTER',
  SET_MEDIA_SORT: 'media/SET_MEDIA_SORT',
} as const;

export const PLAYLIST_ACTIONS = {
  FETCH_PLAYLISTS_REQUEST: 'playlist/FETCH_PLAYLISTS_REQUEST',
  FETCH_PLAYLISTS_SUCCESS: 'playlist/FETCH_PLAYLISTS_SUCCESS',
  FETCH_PLAYLISTS_FAILURE: 'playlist/FETCH_PLAYLISTS_FAILURE',
  
  CREATE_PLAYLIST_REQUEST: 'playlist/CREATE_PLAYLIST_REQUEST',
  CREATE_PLAYLIST_SUCCESS: 'playlist/CREATE_PLAYLIST_SUCCESS',
  CREATE_PLAYLIST_FAILURE: 'playlist/CREATE_PLAYLIST_FAILURE',
  
  UPDATE_PLAYLIST_REQUEST: 'playlist/UPDATE_PLAYLIST_REQUEST',
  UPDATE_PLAYLIST_SUCCESS: 'playlist/UPDATE_PLAYLIST_SUCCESS',
  UPDATE_PLAYLIST_FAILURE: 'playlist/UPDATE_PLAYLIST_FAILURE',
  
  DELETE_PLAYLIST_REQUEST: 'playlist/DELETE_PLAYLIST_REQUEST',
  DELETE_PLAYLIST_SUCCESS: 'playlist/DELETE_PLAYLIST_SUCCESS',
  DELETE_PLAYLIST_FAILURE: 'playlist/DELETE_PLAYLIST_FAILURE',
  
  ADD_ITEMS_TO_PLAYLIST: 'playlist/ADD_ITEMS_TO_PLAYLIST',
  REMOVE_ITEMS_FROM_PLAYLIST: 'playlist/REMOVE_ITEMS_FROM_PLAYLIST',
  REORDER_PLAYLIST_ITEMS: 'playlist/REORDER_PLAYLIST_ITEMS',
} as const;

export const PLAYBACK_ACTIONS = {
  START_PLAYBACK_REQUEST: 'playback/START_PLAYBACK_REQUEST',
  START_PLAYBACK_SUCCESS: 'playback/START_PLAYBACK_SUCCESS',
  START_PLAYBACK_FAILURE: 'playback/START_PLAYBACK_FAILURE',
  
  STOP_PLAYBACK_REQUEST: 'playback/STOP_PLAYBACK_REQUEST',
  STOP_PLAYBACK_SUCCESS: 'playback/STOP_PLAYBACK_SUCCESS',
  
  CONTROL_PLAYBACK_REQUEST: 'playback/CONTROL_PLAYBACK_REQUEST',
  CONTROL_PLAYBACK_SUCCESS: 'playback/CONTROL_PLAYBACK_SUCCESS',
  CONTROL_PLAYBACK_FAILURE: 'playback/CONTROL_PLAYBACK_FAILURE',
  
  FETCH_PLAYBACK_STATUS_REQUEST: 'playback/FETCH_PLAYBACK_STATUS_REQUEST',
  FETCH_PLAYBACK_STATUS_SUCCESS: 'playback/FETCH_PLAYBACK_STATUS_SUCCESS',
  FETCH_PLAYBACK_STATUS_FAILURE: 'playback/FETCH_PLAYBACK_STATUS_FAILURE',
  
  UPDATE_PLAYBACK_STATUS: 'playback/UPDATE_PLAYBACK_STATUS',
} as const;

export const SYNC_ACTIONS = {
  START_SYNC_REQUEST: 'sync/START_SYNC_REQUEST',
  START_SYNC_SUCCESS: 'sync/START_SYNC_SUCCESS',
  START_SYNC_FAILURE: 'sync/START_SYNC_FAILURE',
  
  CANCEL_SYNC_REQUEST: 'sync/CANCEL_SYNC_REQUEST',
  CANCEL_SYNC_SUCCESS: 'sync/CANCEL_SYNC_SUCCESS',
  
  FETCH_SYNC_STATUS_REQUEST: 'sync/FETCH_SYNC_STATUS_REQUEST',
  FETCH_SYNC_STATUS_SUCCESS: 'sync/FETCH_SYNC_STATUS_SUCCESS',
  FETCH_SYNC_STATUS_FAILURE: 'sync/FETCH_SYNC_STATUS_FAILURE',
  
  UPDATE_SYNC_PROGRESS: 'sync/UPDATE_SYNC_PROGRESS',
} as const;

export const SETTINGS_ACTIONS = {
  FETCH_SETTINGS_REQUEST: 'settings/FETCH_SETTINGS_REQUEST',
  FETCH_SETTINGS_SUCCESS: 'settings/FETCH_SETTINGS_SUCCESS',
  FETCH_SETTINGS_FAILURE: 'settings/FETCH_SETTINGS_FAILURE',
  
  UPDATE_SETTINGS_REQUEST: 'settings/UPDATE_SETTINGS_REQUEST',
  UPDATE_SETTINGS_SUCCESS: 'settings/UPDATE_SETTINGS_SUCCESS',
  UPDATE_SETTINGS_FAILURE: 'settings/UPDATE_SETTINGS_FAILURE',
  
  TOGGLE_THEME: 'settings/TOGGLE_THEME',
} as const;
